### ISSUE TITLE
Cannot run the recognizer

### ISSUE THREAD

**Issue by NirChachmovitz** [Numenorean/ShazamAPI#3]
Hi!
I'm trying to run the code, but i get the following error:

`C:\Users\****\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
C:\Users\****\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "C:/Users/****/shazam_executer.py", line 8, in <module>
    print(next(recognize_generator))
  File "C:\Users\****\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ShazamAPI\api.py", line 31, in recognizeSong
    self.audio = self.normalizateAudioData(self.songData)
  File "C:\Users\****\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ShazamAPI\api.py", line 63, in normalizateAudioData
    audio = AudioSegment.from_file(BytesIO(songData))
  File "C:\Users\****\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pydub\audio_segment.py", line 685, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "C:\Users\****\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Users\****\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\****\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

I suppose it is because I didn't add ffprobe and ffmpeg to path, but what path are you talking about?
thanks!

**Comment by Numenorean** [comment]
Hello. You just need to add it to path. What OS do you use?

**Comment by Snitzelberg** [comment]
Hi, I have the same error, i'm using Windows 10

**Comment by ommex** [comment]
Just adding a for Windows compiled ffmpeg version (3x exe-files) to the Same Directory you are working in solved it for me.
https://www.gyan.dev/ffmpeg/builds/

**Comment by r-silver1** [comment]
> Just adding a for Windows compiled ffmpeg version (3x exe-files) to the Same Directory you are working in solved it for me. https://www.gyan.dev/ffmpeg/builds/

Same here, thanks! I think it's probably due to me working in a virtual environment?
